API:
  KSY:
    KAKAO-API-KEY: 366a2020960871528c2516aa01d613d3
    DATA-API-KEY: 8NE4DPVP-8NE4-8NE4-8NE4-8NE4DPVPYA
  KCY:
    X-Naver-Client-Id: j_ESN5fWGldw8kKhuSyo
    X-Naver-Client-Secret: rCzbCfedgU
  WHR:
    DRUG-API-KEY: TQAJaB6Ur9zvncVuex1SXBbgM32KLZxqw74PDvkzv10S43Nw439JSLLSFYkMN30j9SsLJQcDbuSWdokoCgAuHg%3D%3D